spring.application.name: Project viewer

#app settings
auth.url: https://cloud.memsource.com/web/api2/v1/auth/login
project.list.url: https://cloud.memsource.com/web/api2/v1/projects

#H2 storage
server.port: 8088
spring.h2.console.enabled: true
spring.datasource.plateform: h2
spring.datasource.url: jdbc:h2:mem:users

#web settings
spring.thymeleaf.cache: false
spring.thymeleaf.enabled: true
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html


